export const alphabetData = [
  { letter: 'A', uppercase: 'A', lowercase: 'a', word: 'Apple', wordImage: '🍎' },
  { letter: 'B', uppercase: 'B', lowercase: 'b', word: 'Ball', wordImage: '⚽' },
  { letter: 'C', uppercase: 'C', lowercase: 'c', word: 'Cat', wordImage: '🐱' },
  { letter: 'D', uppercase: 'D', lowercase: 'd', word: 'Dog', wordImage: '🐶' },
  { letter: 'E', uppercase: 'E', lowercase: 'e', word: 'Elephant', wordImage: '🐘' },
  { letter: 'F', uppercase: 'F', lowercase: 'f', word: 'Fish', wordImage: '🐟' },
  { letter: 'G', uppercase: 'G', lowercase: 'g', word: 'Grapes', wordImage: '🍇' },
  { letter: 'H', uppercase: 'H', lowercase: 'h', word: 'Hat', wordImage: '🎩' },
  { letter: 'I', uppercase: 'I', lowercase: 'i', word: 'Igloo', wordImage: '🏠' },
  { letter: 'J', uppercase: 'J', lowercase: 'j', word: 'Juice', wordImage: '🧃' },
  { letter: 'K', uppercase: 'K', lowercase: 'k', word: 'Kite', wordImage: '🪁' },
  { letter: 'L', uppercase: 'L', lowercase: 'l', word: 'Lion', wordImage: '🦁' },
  { letter: 'M', uppercase: 'M', lowercase: 'm', word: 'Moon', wordImage: '🌙' },
  { letter: 'N', uppercase: 'N', lowercase: 'n', word: 'Nest', wordImage: '🪺' },
  { letter: 'O', uppercase: 'O', lowercase: 'o', word: 'Orange', wordImage: '🍊' },
  { letter: 'P', uppercase: 'P', lowercase: 'p', word: 'Pig', wordImage: '🐷' },
  { letter: 'Q', uppercase: 'Q', lowercase: 'q', word: 'Queen', wordImage: '👑' },
  { letter: 'R', uppercase: 'R', lowercase: 'r', word: 'Rabbit', wordImage: '🐰' },
  { letter: 'S', uppercase: 'S', lowercase: 's', word: 'Sun', wordImage: '☀️' },
  { letter: 'T', uppercase: 'T', lowercase: 't', word: 'Tree', wordImage: '🌳' },
  { letter: 'U', uppercase: 'U', lowercase: 'u', word: 'Umbrella', wordImage: '☂️' },
  { letter: 'V', uppercase: 'V', lowercase: 'v', word: 'Violin', wordImage: '🎻' },
  { letter: 'W', uppercase: 'W', lowercase: 'w', word: 'Watermelon', wordImage: '🍉' },
  { letter: 'X', uppercase: 'X', lowercase: 'x', word: 'Xylophone', wordImage: '🎵' },
  { letter: 'Y', uppercase: 'Y', lowercase: 'y', word: 'Yacht', wordImage: '⛵' },
  { letter: 'Z', uppercase: 'Z', lowercase: 'z', word: 'Zebra', wordImage: '🦓' },
];
